[build]
  base = "emotion-sphere-ui"
  command = "npm run build"
  publish = "emotion-sphere-ui/dist"

[[redirects]]
  from = "/api/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
