-- Migration 0051: 国际化阶段一 —— 种子内容英文回填（直接写入，幂等：仅填空值）。
-- 由人工翻译生成（圣经体英文/ESV 专名）。重复执行安全。

-- bible_territories
UPDATE bible_territories SET description_en='Territory of the tribe of Judah (teaching illustration).' WHERE id='tribe-judah' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Benjamin (teaching illustration).' WHERE id='tribe-benjamin' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Ephraim (teaching illustration).' WHERE id='tribe-ephraim' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Manasseh (West) (teaching illustration).' WHERE id='tribe-manasseh-west' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Manasseh (East) (teaching illustration).' WHERE id='tribe-manasseh-east' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Dan (teaching illustration).' WHERE id='tribe-dan' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Asher (teaching illustration).' WHERE id='tribe-asher' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Naphtali (teaching illustration).' WHERE id='tribe-naphtali' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Zebulun (teaching illustration).' WHERE id='tribe-zebulun' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Issachar (teaching illustration).' WHERE id='tribe-issachar' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Gad (teaching illustration).' WHERE id='tribe-gad' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Reuben (teaching illustration).' WHERE id='tribe-reuben' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Territory of the tribe of Simeon (teaching illustration).' WHERE id='tribe-simeon' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Sphere of the Assyrian Empire (teaching illustration).' WHERE id='empire-assyria' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Sphere of the Babylonian Empire (teaching illustration).' WHERE id='empire-babylon' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Sphere of the Persian Empire (teaching illustration).' WHERE id='empire-persia' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Sphere of the Greek Empire (teaching illustration).' WHERE id='empire-greece' AND (description_en IS NULL OR description_en='');
UPDATE bible_territories SET description_en='Sphere of the Roman Empire (teaching illustration).' WHERE id='empire-rome' AND (description_en IS NULL OR description_en='');

-- bible_events
UPDATE bible_events SET description_en='Israel was oppressed by Cushan-Rishathaim; God raised up Othniel to deliver them.', spiritual_meaning_en='God hears the cry of His people and raises up a deliverer.' WHERE id='judge-othniel' AND (description_en IS NULL OR description_en='');
UPDATE bible_events SET description_en='Ehud, a left-handed man, struck down Eglon king of Moab and freed Israel from bondage.', spiritual_meaning_en='God can accomplish deliverance through those whom others despise.' WHERE id='judge-ehud' AND (description_en IS NULL OR description_en='');
UPDATE bible_events SET description_en='Deborah stirred up Barak, and they routed Sisera by the river Kishon.', spiritual_meaning_en='Faith and obedience bring rest to the whole land.' WHERE id='judge-deborah' AND (description_en IS NULL OR description_en='');
UPDATE bible_events SET description_en='When Midian oppressed Israel, Gideon led three hundred men in a night attack.', spiritual_meaning_en='God''s deliverance is shown through human weakness.' WHERE id='judge-gideon' AND (description_en IS NULL OR description_en='');
UPDATE bible_events SET description_en='The rejected Jephthah was called back and defeated the Ammonites, yet paid dearly for a rash vow.', spiritual_meaning_en='God exalts the rejected; vows are to be made with reverence.' WHERE id='judge-jephthah' AND (description_en IS NULL OR description_en='');
UPDATE bible_events SET description_en='Samson the Nazirite was mighty in strength and fought the Philistines alone.', spiritual_meaning_en='Forsaking holiness leads to loss of strength; grace is fulfilled through repentance.' WHERE id='judge-samson' AND (description_en IS NULL OR description_en='');

-- bible_prophecies
UPDATE bible_prophecies SET description_en='Isaiah prophesied that Babylon would be overthrown and left desolate forever.', fulfillment_description_en='In 539 BC Cyrus of Persia captured Babylon.' WHERE id='isaiah-13-babylon' AND (description_en IS NULL OR description_en='');
UPDATE bible_prophecies SET description_en='Concerning Moab: in a single night her cities are laid waste and the whole nation wails.' WHERE id='isaiah-15-moab' AND (description_en IS NULL OR description_en='');
UPDATE bible_prophecies SET description_en='Concerning Egypt: internal strife and the drying up of the Nile; in the end she worships God together with Assyria.' WHERE id='isaiah-19-egypt' AND (description_en IS NULL OR description_en='');
UPDATE bible_prophecies SET description_en='Tyre would be broken by many nations, scraped bare like a rock, a place for spreading fishing nets.', fulfillment_description_en='Babylon besieged it for thirteen years; in 332 BC Alexander built a causeway and took the city.' WHERE id='ezekiel-26-tyre' AND (description_en IS NULL OR description_en='');
UPDATE bible_prophecies SET description_en='Nahum prophesied that Nineveh would be overthrown by flood and sword and left desolate forever.', fulfillment_description_en='In 612 BC the allied forces of Babylon and Media captured Nineveh.' WHERE id='nahum-nineveh' AND (description_en IS NULL OR description_en='');
UPDATE bible_prophecies SET description_en='Jeremiah declared that Pharaoh''s army of Egypt would be defeated by Babylon at Carchemish.', fulfillment_description_en='In 605 BC Egypt was crushed at the Battle of Carchemish.' WHERE id='jeremiah-46-egypt' AND (description_en IS NULL OR description_en='');

-- bible_campaigns
UPDATE bible_campaigns SET description_en='God reduced Israel''s army to three hundred men; at night, each holding a trumpet and a torch in a jar, they surrounded the Midianite camp, blew the trumpets, shouted, and smashed the jars. The whole Midianite army panicked, turned on one another, and fled toward the Jordan.' WHERE id='gideon' AND (description_en IS NULL OR description_en='');

-- geo_events（按中文 title 匹配）
UPDATE geo_events SET title_en='Setting Out After the Passover', summary_en='After eating the Passover lamb, the Israelites set out from Rameses toward Succoth—about six hundred thousand men on foot.' WHERE title='逾越节之后出发' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The LORD Guides Day and Night', summary_en='By day a pillar of cloud and by night a pillar of fire went before them to light the way.' WHERE title='耶和华昼夜引导' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Camping at the Edge of the Wilderness', summary_en='They camped at Etham on the edge of the wilderness.' WHERE title='安营在旷野边缘' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Crossing the Red Sea; Pharaoh''s Army Drowned', summary_en='Moses stretched out his staff, the sea parted, and Israel crossed on dry ground; Pharaoh''s chariots and horsemen followed, and the returning waters drowned them.' WHERE title='过红海，法老追兵覆没' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Bitter Water Made Sweet', summary_en='When the people grumbled at the bitter water, the LORD showed Moses a tree to throw into the water, and it became sweet.' WHERE title='苦水变甜' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Twelve Springs and Seventy Palm Trees', summary_en='They came to Elim, where there were twelve springs and seventy palm trees, and camped there by the water.' WHERE title='十二股水泉、七十棵棕树' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Manna and Quail from Heaven', summary_en='In the evening quail covered the camp, and in the morning manna fell like frost—their daily food for forty years.' WHERE title='天降吗哪与鹌鹑' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Water from the Struck Rock', summary_en='When the people had no water, the LORD told Moses to strike the rock at Horeb, and water flowed out for them to drink.' WHERE title='击打磐石出水' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Giving of the Ten Commandments and the Covenant', summary_en='The LORD descended on Mount Sinai in fire, smoke, and thunder, proclaimed the Ten Commandments, and made a covenant with Israel.' WHERE title='颁布十诫与立约' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Craving and the Plague of Quail', summary_en='The people craved meat; the LORD sent vast quantities of quail, then struck the greedy with a severe plague—hence the name ''Kibroth-hattaavah'' (Graves of Craving).' WHERE title='贪欲与鹌鹑之灾' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Miriam and Aaron Speak Against Moses', summary_en='Miriam and Aaron spoke against Moses because of his wife; Miriam became leprous and was healed after Moses interceded for her.' WHERE title='米利暗与亚伦毁谤摩西' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Harbor at the North End of the Red Sea', summary_en='Here on the Gulf of Aqaba, Solomon later built a fleet''s harbor; the Israelites had once camped here.' WHERE title='红海北端的港口' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Twelve Spies Scout Canaan', summary_en='After the spies'' report, the people grumbled and refused to enter Canaan; they were sentenced to wander forty years in the wilderness until that generation perished.' WHERE title='十二个探子窥探迦南' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Death of Aaron', summary_en='On the top of Mount Hor, Aaron handed his priestly garments to Eleazar and died there; the whole congregation mourned him thirty days.' WHERE title='亚伦逝世' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Bronze Serpent and the Fiery Serpents', summary_en='When the people grumbled, the LORD sent fiery serpents that killed many; Moses made a bronze serpent on a pole, and all who looked at it lived.' WHERE title='铜蛇与火蛇' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Moses Views the Promised Land', summary_en='Moses went up to the top of Pisgah on Mount Nebo, and the LORD showed him all the land: this is the land I swore to Abraham, Isaac, and Jacob.' WHERE title='摩西遥望应许之地' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Oracle of Balaam', summary_en='Balak king of Moab hired Balaam to curse Israel, but God moved him to bless them again and again, foretelling: ''A star shall come out of Jacob.''' WHERE title='巴兰的预言' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Sending Church of the Mission', summary_en='The church at Antioch fasted and prayed, and the Holy Spirit sent out Barnabas and Saul (Paul) to preach; all three journeys began here.' WHERE title='宣教事工的母会' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Preaching in Cyprus', summary_en='Arriving at Salamis, they proclaimed the word of God in the Jewish synagogues.' WHERE title='在居比路（塞浦路斯）传道' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Elymas the Sorcerer Struck Blind', summary_en='Paul rebuked Elymas the sorcerer, who was immediately blinded; the proconsul Sergius Paulus, amazed, believed in the Lord.' WHERE title='行法术的以吕马受罚' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='John Mark Leaves the Team', summary_en='At Perga in Pamphylia, John Mark left them and returned to Jerusalem.' WHERE title='约翰马可离队' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Synagogue Preaching; Turning to the Gentiles', summary_en='Paul recounted the history of salvation in the synagogue; when the Jews opposed him out of jealousy, he declared he would turn to the Gentiles, who gladly received the word.' WHERE title='会堂讲道，转向外邦' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Nearly Stoned', summary_en='Many believed, but the city was divided; when some sought to mistreat and stone them, the two fled to Lystra and Derbe.' WHERE title='险被石头打' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Healing the Man Lame from Birth', summary_en='Paul healed a lame man; the crowds thought the gods (Zeus and Hermes) had come down and tried to offer sacrifices, but the two earnestly restrained them.' WHERE title='医好生来瘸腿的人' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Macedonian Vision', summary_en='In the night Paul saw a vision: a man of Macedonia begging him to come and help; thus the gospel first entered Europe.' WHERE title='马其顿的异象' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Lydia Comes to the Lord', summary_en='Lydia, a seller of purple cloth, heard the message; the Lord opened her heart, and she and her household were baptized—the first believer in Europe.' WHERE title='吕底亚归主' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Reasoning for Three Sabbaths', summary_en='For three Sabbaths Paul reasoned in the synagogue; many believed, while the unbelieving Jews stirred up a mob.' WHERE title='三个安息日辩道' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Receiving Eagerly, Searching the Scriptures Daily', summary_en='The Bereans were more noble than the Thessalonians; they received the word eagerly and searched the Scriptures daily to see whether these things were so.' WHERE title='甘心领受、天天考查圣经' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Areopagus Sermon on the ''Unknown God''', summary_en='Standing at the Areopagus, Paul used the altar ''to an unknown god'' to proclaim the Creator and the gospel of the resurrection.' WHERE title='亚略巴古讲"未识之神"' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='A Year and a Half with Priscilla and Aquila', summary_en='Paul stayed and worked with the tentmakers Aquila and Priscilla, remaining a year and six months teaching the word of God.' WHERE title='住一年半，与百基拉亚居拉同工' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Two Years, and the Word Spread', summary_en='Paul reasoned daily in the hall of Tyrannus for two years, so that all the residents of Asia heard the word of the Lord.' WHERE title='两年之久，主道兴旺' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Farewell to the Ephesian Elders', summary_en='Paul summoned the Ephesian elders to Miletus, charging them to shepherd the church of God; with much weeping they bade him farewell.' WHERE title='向以弗所长老告别' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='The Start of the Journey to Rome as a Prisoner', summary_en='Paul and other prisoners were handed over to the centurion Julius, and from here they boarded a ship for Italy.' WHERE title='押往罗马的起点' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Journey''s End and the Arrest', summary_en='Paul returned to Jerusalem, was mobbed by the Jews in the temple, and was taken into custody by the Roman tribune—beginning the road to trial in Rome.' WHERE title='旅程的终点与被捕' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Paul Warns of the Danger of Sailing', summary_en='Paul advised against sailing on, but the centurion trusted the ship''s owner, and the majority decided to set sail from Fair Havens.' WHERE title='保罗预警航行危险' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Saved from Shipwreck; Unharmed by the Viper', summary_en='When the ship broke up, all swam ashore to the island of Malta; a viper fastened on Paul''s hand but he suffered no harm, and the islanders thought he was a god.' WHERE title='海难得救、毒蛇无害' AND (title_en IS NULL OR title_en='');
UPDATE geo_events SET title_en='Bold Preaching in Rome', summary_en='Paul lived two years in his own rented house, boldly proclaiming the kingdom of God and teaching about the Lord Jesus Christ, and no one hindered him.' WHERE title='在罗马放胆传道' AND (title_en IS NULL OR title_en='');
