-- Migration 0145: Right-to-erasure (GDPR/PIPL) — purge a user's personal data.
--
-- Provides erase_user_data(p_email) which deletes every email-keyed row for a
-- user across all personal tables, plus the user_id-keyed personal tables, then
-- scrubs the user's PII from shared/owned content (churches, orgs, tenants,
-- public templates) WITHOUT deleting that shared content (deleting it would
-- destroy data belonging to other members), and finally removes the account row.
--
-- Idempotent & defensive: every table is guarded with to_regclass so a missing
-- table is skipped rather than erroring. Table list was generated by scanning
-- backend/migrations/*.sql for columns named email / user_id / owner_email /
-- created_by_email (see README_right_to_erasure.md).
--
-- NOT wired to any endpoint here — wiring an authenticated /api/account/erase
-- route lives in main.py (owned by another agent) and is a FOLLOW-UP. Run
-- manually as:  SELECT * FROM erase_user_data('user@example.com');
-- Returns one (table_name, rows_deleted) row per table touched.

CREATE OR REPLACE FUNCTION erase_user_data(p_email text)
RETURNS TABLE(table_name text, rows_deleted bigint) AS $$
DECLARE
    t text;
    n bigint;
    email_tables text[] := ARRAY[
        'accountability_checkins', 'accountability_goals', 'accountability_group_checkins', 'accountability_group_goals',
        'accountability_group_members', 'affections_entries', 'agent_events', 'agent_runs',
        'ai_formation_profiles', 'ai_formation_recommendations', 'ai_tutor_conversations', 'apologetics_cases',
        'apologetics_dialogues', 'attachment_patterns', 'attachment_sessions', 'book_marks',
        'calling_patterns', 'care_consent', 'care_signals', 'chinese_devotion_entries',
        'church_life_checkins', 'church_life_rhythms', 'church_members', 'church_reentry_plans',
        'community_comments', 'community_feedback', 'community_guardians', 'community_post_amens',
        'community_posts', 'contentment_entries', 'crisis_risk_assessments', 'cultural_discernment_cases',
        'daily_formation_plans', 'decision_cases', 'decision_discernments', 'delight_entries',
        'diagnostic_findings', 'diagnostic_sessions', 'disciple_assessments', 'disciple_profiles',
        'discipleship_assessments', 'discipleship_path_steps', 'distorted_beliefs', 'doctrine_learning_paths',
        'doctrine_lesson_progress', 'doctrine_reflections', 'eh_entries', 'examen_entries',
        'fasting_checkins', 'fasting_plans', 'fasting_reviews', 'formation_agent_sessions',
        'formation_batch1_4_records', 'formation_events', 'formation_grace_evidence', 'formation_integrity_audits',
        'formation_liturgy_entries', 'formation_metric_snapshots', 'formation_os_events', 'formation_os_records',
        'formation_overload_signals', 'formation_plans', 'formation_reports', 'formation_review_reports',
        'formation_subscriptions', 'formation_task_logs', 'formation_tasks', 'formation_tenant_members',
        'fruit_assessment_scores', 'fruit_assessments', 'fruit_scores', 'gift_assessments',
        'gospel_diagnoses', 'gratitude_entries', 'group_prayer_requests', 'growth_plans',
        'guardian_alerts', 'guardian_behavior_patterns', 'guardian_devotion_entries', 'guardian_emotion_events',
        'guardian_idol_signals', 'guardian_memories', 'guardian_messages', 'guardian_prayer_entries',
        'guardian_profiles', 'guardian_spiritual_checkins', 'guardian_states', 'intercession_prayer_logs',
        'intercession_request_updates', 'intercession_requests', 'intercession_targets', 'know_god_entries',
        'lament_entries', 'lament_prayers', 'lectio_sessions', 'master_acceptance_checks',
        'master_build_runs', 'memory_consent_rules', 'memory_verses', 'ministry_matches',
        'mission_commitments', 'mission_life_profiles', 'mission_project_logs', 'mission_projects',
        'misuse_risks', 'narrative_rewrites', 'ordo_amoris_entries', 'organization_memberships',
        'pilgrim_visits', 'platform_admins', 'prayer_rule_sessions', 'prayer_rule_slots',
        'prayer_rules', 'presence_checkins', 'presence_rules', 'psalm_prayer_sessions',
        'push_subscriptions', 'reading_plan_enrollment', 'reading_plan_progress', 'renovation_entries',
        'resource_bookmarks', 'rest_audits', 'rest_boundary_rules', 'review_logs',
        'sabbath_plans', 'sabbath_sessions', 'semantic_index', 'sfds_users',
        'simplicity_actions', 'simplicity_audits', 'spirits_entries', 'spiritual_checkups',
        'spiritual_memory_items', 'spiritual_profiles', 'strength_profiles', 'subscriptions',
        'suffering_care_plans', 'suffering_cases', 'temptation_checkins', 'temptation_failure_reviews',
        'temptation_plans', 'tender_heart_entries', 'testimonies', 'theological_review_logs',
        'timeline_learning_sessions', 'tutor_messages', 'tutor_threads', 'union_entries',
        'user_church_connections', 'user_consents', 'user_discipleship_paths', 'user_doctrine_progress',
        'vocation_worldview_cases', 'voice_group_members', 'waiting_cases', 'waiting_reflections',
        'weekly_reviews', 'worldview_assessments', 'worldview_beliefs', 'worldview_dimension_scores',
        'worldview_metric_snapshots', 'worldview_presuppositions', 'worldview_profiles', 'worldview_responses'
    ];
    userid_tables text[] := ARRAY[
        'habit_daily_notes', 'mvfe_pipeline_stats', 'spiritual_holy_life_day_logs', 'user_verse_feedback'
    ];
BEGIN
    IF p_email IS NULL OR length(trim(p_email)) = 0 THEN
        RAISE EXCEPTION 'erase_user_data: p_email is required';
    END IF;

    -- 1) email-keyed personal tables
    FOREACH t IN ARRAY email_tables LOOP
        IF to_regclass(quote_ident(t)) IS NOT NULL THEN
            EXECUTE format('DELETE FROM %I WHERE email = $1', t) USING p_email;
            GET DIAGNOSTICS n = ROW_COUNT;
            table_name := t; rows_deleted := n; RETURN NEXT;
        END IF;
    END LOOP;

    -- 2) user_id-keyed personal tables (user_id may be a numeric users.id or the
    --    email itself; resolve both).
    FOREACH t IN ARRAY userid_tables LOOP
        IF to_regclass(quote_ident(t)) IS NOT NULL THEN
            EXECUTE format(
                'DELETE FROM %I WHERE user_id::text = $1 '
                'OR user_id::text IN (SELECT id::text FROM users WHERE email = $1)', t)
                USING p_email;
            GET DIAGNOSTICS n = ROW_COUNT;
            table_name := t; rows_deleted := n; RETURN NEXT;
        END IF;
    END LOOP;

    -- 3) shared/owned content: scrub the user's PII (owner attribution) but keep
    --    the row so co-owned data survives. Reassigning ownership is a manual
    --    follow-up if the entity must outlive the erased owner.
    IF to_regclass('accountability_groups') IS NOT NULL THEN
        UPDATE accountability_groups SET created_by_email = '' WHERE created_by_email = p_email;
        GET DIAGNOSTICS n = ROW_COUNT;
        table_name := 'accountability_groups.created_by_email'; rows_deleted := n; RETURN NEXT;
    END IF;
    IF to_regclass('church_profiles') IS NOT NULL THEN
        UPDATE church_profiles SET created_by_email = '' WHERE created_by_email = p_email;
        GET DIAGNOSTICS n = ROW_COUNT;
        table_name := 'church_profiles.created_by_email'; rows_deleted := n; RETURN NEXT;
    END IF;
    IF to_regclass('churches') IS NOT NULL THEN
        UPDATE churches SET owner_email = '' WHERE owner_email = p_email;
        GET DIAGNOSTICS n = ROW_COUNT;
        table_name := 'churches.owner_email'; rows_deleted := n; RETURN NEXT;
    END IF;
    IF to_regclass('formation_tenants') IS NOT NULL THEN
        UPDATE formation_tenants SET owner_email = '' WHERE owner_email = p_email;
        GET DIAGNOSTICS n = ROW_COUNT;
        table_name := 'formation_tenants.owner_email'; rows_deleted := n; RETURN NEXT;
    END IF;
    IF to_regclass('organizations') IS NOT NULL THEN
        UPDATE organizations SET owner_email = '' WHERE owner_email = p_email;
        GET DIAGNOSTICS n = ROW_COUNT;
        table_name := 'organizations.owner_email'; rows_deleted := n; RETURN NEXT;
    END IF;
    IF to_regclass('prayer_templates') IS NOT NULL THEN
        UPDATE prayer_templates SET created_by_email = '' WHERE created_by_email = p_email;
        GET DIAGNOSTICS n = ROW_COUNT;
        table_name := 'prayer_templates.created_by_email'; rows_deleted := n; RETURN NEXT;
    END IF;
    -- 4) the account row itself (last, after dependents are gone).
    IF to_regclass('users') IS NOT NULL THEN
        DELETE FROM users WHERE email = p_email;
        GET DIAGNOSTICS n = ROW_COUNT;
        table_name := 'users'; rows_deleted := n; RETURN NEXT;
    END IF;

    RETURN;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION erase_user_data(text) IS
    'Right-to-erasure: delete all personal rows for an email, scrub shared-owner PII, drop the account. Run manually; wiring to an API endpoint is a follow-up.';
