-- MissionBridge Skill 06: participant-owned goals and explainable care plans.
CREATE TABLE IF NOT EXISTS mission_bridge_participant_profiles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,display_name TEXT,language TEXT NOT NULL DEFAULT 'zh-CN',accessibility_preferences JSONB NOT NULL DEFAULT '{}'::jsonb,contact_preferences JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS mission_bridge_participant_strengths(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,label TEXT NOT NULL,evidence TEXT,confirmed_by_participant BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_participant_goals(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,enrollment_id UUID REFERENCES mission_bridge_enrollments(id),title TEXT NOT NULL,success_description TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'proposed',participant_confirmed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_care_plans(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,enrollment_id UUID REFERENCES mission_bridge_enrollments(id),title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',rationale TEXT NOT NULL,participant_approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_care_actions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,care_plan_id UUID NOT NULL REFERENCES mission_bridge_care_plans(id),title TEXT NOT NULL,action_type TEXT NOT NULL,due_date DATE,status TEXT NOT NULL DEFAULT 'pending',suggestion_reason TEXT,completed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_progress_notes(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,enrollment_id UUID REFERENCES mission_bridge_enrollments(id),author_user_id TEXT NOT NULL,note TEXT NOT NULL,sensitivity TEXT NOT NULL DEFAULT 'normal',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(sensitivity IN('normal','restricted','safeguarding')));
CREATE TABLE IF NOT EXISTS mission_bridge_referrals(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,enrollment_id UUID REFERENCES mission_bridge_enrollments(id),referral_type TEXT NOT NULL,reason_summary TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'requested',consent_recorded BOOLEAN NOT NULL DEFAULT FALSE,provider_id UUID,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_mb_goals_user ON mission_bridge_participant_goals(tenant_id,user_id,status);
CREATE INDEX IF NOT EXISTS idx_mb_care_user ON mission_bridge_care_plans(tenant_id,user_id,status);
