-- MissionBridge Skill 09: cohorts, mentoring, supervision and human certification.
CREATE TABLE IF NOT EXISTS mission_bridge_cohorts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,program_id TEXT NOT NULL,program_version TEXT NOT NULL,title TEXT NOT NULL,capacity INTEGER NOT NULL CHECK(capacity BETWEEN 2 AND 200),status TEXT NOT NULL DEFAULT 'forming',starts_at TIMESTAMPTZ,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_cohort_members(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,cohort_id UUID NOT NULL REFERENCES mission_bridge_cohorts(id),user_id TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'participant',status TEXT NOT NULL DEFAULT 'active',joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(cohort_id,user_id));
CREATE TABLE IF NOT EXISTS mission_bridge_sessions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,cohort_id UUID NOT NULL REFERENCES mission_bridge_cohorts(id),title TEXT NOT NULL,session_at TIMESTAMPTZ NOT NULL,facilitator_user_id TEXT,status TEXT NOT NULL DEFAULT 'planned',feedback_summary TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_session_attendance(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,session_id UUID NOT NULL REFERENCES mission_bridge_sessions(id),user_id TEXT NOT NULL,attendance TEXT NOT NULL,participant_feedback TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(session_id,user_id));
CREATE TABLE IF NOT EXISTS mission_bridge_mentor_profiles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,capacity INTEGER NOT NULL DEFAULT 1 CHECK(capacity BETWEEN 1 AND 20),matching_preferences JSONB NOT NULL DEFAULT '{}'::jsonb,safeguarding_trained_at TIMESTAMPTZ,power_boundaries_trained_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS mission_bridge_mentor_assignments(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,mentor_user_id TEXT NOT NULL,participant_user_id TEXT NOT NULL,program_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'proposed',preference_match JSONB NOT NULL DEFAULT '{}'::jsonb,participant_consented_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,mentor_user_id,participant_user_id,program_id));
CREATE TABLE IF NOT EXISTS mission_bridge_mentor_supervisions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,mentor_user_id TEXT NOT NULL,supervisor_user_id TEXT NOT NULL,summary TEXT NOT NULL,safeguarding_concerns BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_facilitator_profiles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'trainee',deput_ready BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS mission_bridge_facilitator_observations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,facilitator_user_id TEXT NOT NULL,observer_user_id TEXT NOT NULL,session_id UUID,observation TEXT NOT NULL,power_boundary_safe BOOLEAN NOT NULL,safeguarding_safe BOOLEAN NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_facilitator_certifications(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,facilitator_user_id TEXT NOT NULL,certification_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',approved_by TEXT,approved_at TIMESTAMPTZ,expires_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_trainer_candidates(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,evidence JSONB NOT NULL DEFAULT '{}'::jsonb,status TEXT NOT NULL DEFAULT 'draft',submitted_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_trainer_approvals(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,candidate_id UUID NOT NULL REFERENCES mission_bridge_trainer_candidates(id),decision TEXT NOT NULL,reviewer_user_id TEXT NOT NULL,rationale TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_mb_cohorts_program ON mission_bridge_cohorts(tenant_id,program_id,status);
CREATE INDEX IF NOT EXISTS idx_mb_mentor_capacity ON mission_bridge_mentor_assignments(tenant_id,mentor_user_id,status);
