-- MissionBridge Skill 07: versioned, reviewed and source-backed content/RAG.
CREATE TABLE IF NOT EXISTS mission_bridge_content_catalog(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,program_id TEXT,content_type TEXT NOT NULL,title TEXT NOT NULL,created_by TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',published_version INTEGER,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_content_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_id UUID NOT NULL REFERENCES mission_bridge_content_catalog(id),version INTEGER NOT NULL,language TEXT NOT NULL,content_class TEXT NOT NULL,body TEXT NOT NULL,core_meaning_hash TEXT NOT NULL,reading_level TEXT NOT NULL DEFAULT 'standard',created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(content_id,version,language,reading_level));
CREATE TABLE IF NOT EXISTS mission_bridge_content_sources(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_version_id UUID NOT NULL REFERENCES mission_bridge_content_versions(id),author TEXT NOT NULL,source_title TEXT NOT NULL,source_url TEXT,copyright_holder TEXT NOT NULL,license TEXT NOT NULL,citation TEXT NOT NULL,verified BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS mission_bridge_content_reviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_version_id UUID NOT NULL REFERENCES mission_bridge_content_versions(id),review_type TEXT NOT NULL CHECK(review_type IN('theological','cultural','safeguarding','accessibility')),decision TEXT NOT NULL CHECK(decision IN('approved','changes_requested','rejected')),reviewer_user_id TEXT NOT NULL,notes TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(content_version_id,review_type));
CREATE TABLE IF NOT EXISTS mission_bridge_theological_reviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_version_id UUID NOT NULL,reviews_scripture_accuracy BOOLEAN NOT NULL,distinguishes_interpretation BOOLEAN NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_safeguarding_reviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_version_id UUID NOT NULL,coercion_free BOOLEAN NOT NULL,non_stigmatizing BOOLEAN NOT NULL,professional_boundaries BOOLEAN NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_localization_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_version_id UUID NOT NULL,locale TEXT NOT NULL,media_type TEXT NOT NULL DEFAULT 'text',asset_url TEXT,translator_user_id TEXT,approved BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_reading_level_scores(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_version_id UUID NOT NULL,reading_level TEXT NOT NULL,score NUMERIC,meaning_preserved BOOLEAN NOT NULL DEFAULT FALSE,reviewed_by TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_content_embeddings(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_version_id UUID NOT NULL,embedding JSONB NOT NULL DEFAULT '[]'::jsonb,model TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_content_usage_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,content_id UUID NOT NULL,event_type TEXT NOT NULL,user_id_hash TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_mb_content_published ON mission_bridge_content_catalog(tenant_id,status,published_version,content_type);
CREATE INDEX IF NOT EXISTS idx_mb_content_versions_search ON mission_bridge_content_versions USING GIN(to_tsvector('simple',body));
