BEGIN;
CREATE TABLE IF NOT EXISTS mission_bridge_shift_profiles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,shift_type TEXT NOT NULL CHECK(shift_type IN('night','rotating','irregular')),shift_start TIME,shift_end TIME,notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE,timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS mission_bridge_shift_checkins(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,shift_started_at TIMESTAMPTZ NOT NULL,sleep_minutes INTEGER,fatigue INTEGER NOT NULL CHECK(fatigue BETWEEN 1 AND 5),loneliness INTEGER NOT NULL CHECK(loneliness BETWEEN 1 AND 5),trusted_relationship BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_shift_preparations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,shift_checkin_id UUID REFERENCES mission_bridge_shift_checkins(id),intention TEXT NOT NULL,safety_boundary TEXT NOT NULL,audio_completed BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_post_shift_debriefs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,shift_checkin_id UUID REFERENCES mission_bridge_shift_checkins(id),emotion_label TEXT NOT NULL,release_note TEXT NOT NULL,family_contacted BOOLEAN NOT NULL DEFAULT FALSE,help_requested BOOLEAN NOT NULL DEFAULT FALSE,risk_categories JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_shift_groups(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,site_code TEXT NOT NULL,title TEXT NOT NULL,rotation_window TEXT NOT NULL,meeting_mode TEXT NOT NULL CHECK(meeting_mode IN('onsite','hybrid','async')),status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS mission_bridge_shift_resources(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,resource_type TEXT NOT NULL CHECK(resource_type IN('rest_audio','couple_communication','gaming_risk','gambling_risk','debt_help','career_growth')),content_id UUID REFERENCES mission_bridge_content_catalog(id),published BOOLEAN NOT NULL DEFAULT FALSE);
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['mission_bridge_shift_profiles','mission_bridge_shift_checkins','mission_bridge_shift_preparations','mission_bridge_post_shift_debriefs','mission_bridge_shift_groups','mission_bridge_shift_resources'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id=current_setting(''app.tenant_id'',true)) WITH CHECK (tenant_id=current_setting(''app.tenant_id'',true))',t);END LOOP;END $$;
COMMIT;
