BEGIN;
CREATE TABLE IF NOT EXISTS mission_bridge_caregiver_assessments(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,stress_level INTEGER NOT NULL CHECK(stress_level BETWEEN 1 AND 5),sleep_minutes INTEGER,fatigue INTEGER NOT NULL CHECK(fatigue BETWEEN 1 AND 5),anger_present BOOLEAN NOT NULL DEFAULT FALSE,self_harm_signal BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_caregiver_support_groups(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,title TEXT NOT NULL,meeting_weekday INTEGER CHECK(meeting_weekday BETWEEN 0 AND 6),facilitator_user_id TEXT,status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS mission_bridge_family_responsibility_meetings(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,agenda JSONB NOT NULL DEFAULT '[]'::jsonb,responsibilities JSONB NOT NULL DEFAULT '[]'::jsonb,next_review_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_respite_requests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,duration_minutes INTEGER NOT NULL CHECK(duration_minutes BETWEEN 30 AND 480),support_scope TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'requested',assigned_volunteer_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_caregiver_expressions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,emotion TEXT NOT NULL,expression TEXT NOT NULL,prayer TEXT NOT NULL DEFAULT '',private BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(private=TRUE));
CREATE TABLE IF NOT EXISTS mission_bridge_caregiver_resources(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,resource_type TEXT NOT NULL CHECK(resource_type IN('end_of_life','grief','medical','social_work','legal')),name TEXT NOT NULL,contact_summary TEXT NOT NULL,source_url TEXT NOT NULL,verified BOOLEAN NOT NULL DEFAULT FALSE);
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['mission_bridge_caregiver_assessments','mission_bridge_caregiver_support_groups','mission_bridge_family_responsibility_meetings','mission_bridge_respite_requests','mission_bridge_caregiver_expressions','mission_bridge_caregiver_resources'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id=current_setting(''app.tenant_id'',true)) WITH CHECK (tenant_id=current_setting(''app.tenant_id'',true))',t);END LOOP;END $$;
COMMIT;
