BEGIN;
CREATE TABLE IF NOT EXISTS mission_bridge_metric_definitions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),metric_key TEXT UNIQUE NOT NULL,layer TEXT NOT NULL CHECK(layer IN('north_star','service','growth','safety','replication')),label TEXT NOT NULL,aggregation TEXT NOT NULL,personal_ranking_allowed BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,CHECK(personal_ranking_allowed=FALSE));
CREATE TABLE IF NOT EXISTS mission_bridge_outcome_observations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,program_id TEXT NOT NULL,user_id TEXT NOT NULL,metric_key TEXT NOT NULL REFERENCES mission_bridge_metric_definitions(metric_key),value NUMERIC NOT NULL,evidence_type TEXT NOT NULL,observed_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mission_bridge_metric_snapshots(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,program_id TEXT,period_start DATE NOT NULL,period_end DATE NOT NULL,metric_key TEXT NOT NULL,aggregate_value NUMERIC NOT NULL,sample_size INTEGER NOT NULL,suppressed BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE mission_bridge_outcome_observations ENABLE ROW LEVEL SECURITY;CREATE POLICY tenant_isolation ON mission_bridge_outcome_observations USING(tenant_id=current_setting('app.tenant_id',true)) WITH CHECK(tenant_id=current_setting('app.tenant_id',true));ALTER TABLE mission_bridge_metric_snapshots ENABLE ROW LEVEL SECURITY;CREATE POLICY tenant_isolation ON mission_bridge_metric_snapshots USING(tenant_id=current_setting('app.tenant_id',true)) WITH CHECK(tenant_id=current_setting('app.tenant_id',true));
INSERT INTO mission_bridge_metric_definitions(metric_key,layer,label,aggregation) VALUES
('trusted_relationship','north_star','建立可信任关系','rate'),('needs_matched','north_star','获得真实需要匹配帮助','rate'),('self_agency','north_star','自我行动能力增强','change'),('stable_spiritual_practice','north_star','建立稳定属灵实践','rate'),('serves_others','north_star','成长为能够服事他人','rate'),('reduced_single_leader_dependency','north_star','减少单一领袖依赖','change'),('sustained_outcomes','north_star','项目后成果持续','rate'),
('first_response_time','service','首次响应时间','median'),('program_completion','service','项目完成率','rate'),('referral_completion','service','转介完成率','rate'),('participant_exit','service','用户退出率','rate'),('complaint_resolution_time','service','投诉处理时间','median'),
('goal_completion','growth','目标完成率','rate'),('habit_stability','growth','习惯稳定性','change'),('loneliness_change','growth','孤独感变化','change'),('leadership_change','growth','带领能力变化','change'),('peer_relationship_count','growth','同伴关系数量','average'),
('high_risk_incidents','safety','高风险事件数量','count'),('escalation_timeliness','safety','升级及时性','median'),('unauthorized_access','safety','越权访问','count'),('minor_safety_incidents','safety','未成年人安全事件','count'),('coercive_complaints','safety','强迫性沟通投诉','count'),
('apprentice_rate','replication','副组长培养率','rate'),('local_leader_rate','replication','本地带领者比例','rate'),('participant_to_mentor_approved','replication','参与者转导师人工批准比例','rate'),('post_founder_sustainability','replication','脱离创始团队持续率','rate') ON CONFLICT DO NOTHING;
COMMIT;
