-- Batch 4 course content bodies + Batch 5 supporter portal.
CREATE TABLE IF NOT EXISTS mission_course_catalog(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,course_key TEXT NOT NULL,title TEXT NOT NULL,summary TEXT,course_version INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','review','published','archived')),created_by TEXT NOT NULL,published_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,course_key,course_version));
CREATE TABLE IF NOT EXISTS mission_course_lessons(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,course_id UUID NOT NULL REFERENCES mission_course_catalog(id),lesson_key TEXT NOT NULL,title TEXT NOT NULL,body_markdown TEXT NOT NULL,sequence_order INTEGER NOT NULL DEFAULT 0,estimated_minutes INTEGER CHECK(estimated_minutes BETWEEN 1 AND 600),requires_human_observation BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,course_id,lesson_key));
CREATE TABLE IF NOT EXISTS mission_course_enrollments(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,course_id UUID NOT NULL REFERENCES mission_course_catalog(id),worker_profile_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('active','paused','completed','withdrawn')),enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),completed_at TIMESTAMPTZ,UNIQUE(tenant_id,course_id,worker_profile_id));
CREATE TABLE IF NOT EXISTS mission_lesson_progress(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,enrollment_id UUID NOT NULL REFERENCES mission_course_enrollments(id),lesson_id UUID NOT NULL REFERENCES mission_course_lessons(id),status TEXT NOT NULL DEFAULT 'not_started' CHECK(status IN('not_started','in_progress','submitted','verified','revision_required')),evidence_reference TEXT,verified_by TEXT,verified_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,enrollment_id,lesson_id));
CREATE TABLE IF NOT EXISTS mission_supporter_memberships(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,support_network_id UUID NOT NULL REFERENCES mission_support_networks(id),user_id TEXT NOT NULL,member_type TEXT NOT NULL DEFAULT 'prayer_partner',status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('invited','active','paused','unsubscribed','removed')),visibility_ceiling TEXT NOT NULL DEFAULT 'registered_supporters',joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),unsubscribed_at TIMESTAMPTZ,UNIQUE(tenant_id,support_network_id,user_id));
CREATE TABLE IF NOT EXISTS mission_supporter_preferences(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id TEXT NOT NULL,membership_id UUID NOT NULL REFERENCES mission_supporter_memberships(id),email_enabled BOOLEAN NOT NULL DEFAULT TRUE,push_enabled BOOLEAN NOT NULL DEFAULT TRUE,digest_frequency TEXT NOT NULL DEFAULT 'weekly' CHECK(digest_frequency IN('immediate','daily','weekly','monthly','none')),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(tenant_id,membership_id));
ALTER TABLE mission_course_catalog ENABLE ROW LEVEL SECURITY;ALTER TABLE mission_course_lessons ENABLE ROW LEVEL SECURITY;ALTER TABLE mission_course_enrollments ENABLE ROW LEVEL SECURITY;ALTER TABLE mission_lesson_progress ENABLE ROW LEVEL SECURITY;ALTER TABLE mission_supporter_memberships ENABLE ROW LEVEL SECURITY;ALTER TABLE mission_supporter_preferences ENABLE ROW LEVEL SECURITY;
DO $$DECLARE t TEXT;BEGIN FOREACH t IN ARRAY ARRAY['mission_course_catalog','mission_course_lessons','mission_course_enrollments','mission_lesson_progress','mission_supporter_memberships','mission_supporter_preferences'] LOOP EXECUTE format('DROP POLICY IF EXISTS mission_tenant_isolation ON %I',t);EXECUTE format('CREATE POLICY mission_tenant_isolation ON %I USING(tenant_id=current_setting(''app.tenant_id'',true)) WITH CHECK(tenant_id=current_setting(''app.tenant_id'',true))',t);END LOOP;END$$;
CREATE INDEX IF NOT EXISTS idx_mission_course_status ON mission_course_catalog(tenant_id,status,published_at);CREATE INDEX IF NOT EXISTS idx_mission_supporter_user ON mission_supporter_memberships(tenant_id,user_id,status);
