-- EMD-OS Batch 8: Formation Twin bridge, identity alignment, prayer routing, rule of life,
-- cross-system plans, pastoral summaries, handoffs, group practice and community feedback.
-- Pastors and group leaders have no default access; every share is field-level, previewed,
-- expiring and revocable.

CREATE TABLE IF NOT EXISTS formation_twin_emd_twin_bridges (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    bridge_id VARCHAR(80) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'WRITTEN',
    written_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    held_back_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    written_count INTEGER NOT NULL DEFAULT 0 CHECK(written_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE(email, bridge_id),
    CHECK(status IN ('WRITTEN','NOTHING_TO_WRITE','BLOCKED_NO_CONSENT'))
);

CREATE TABLE IF NOT EXISTS formation_twin_emd_identity_alignments (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    alignment_id VARCHAR(80) NOT NULL,
    layers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    gaps_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    missing_layers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    theology_pack_id VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE(email, alignment_id)
);

CREATE TABLE IF NOT EXISTS formation_twin_emd_prayer_routings (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    routing_id VARCHAR(80) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'READY',
    forms_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    theology_pack_id VARCHAR(80),
    content_source VARCHAR(48) NOT NULL DEFAULT 'CURATED_THEOLOGICAL_PROPOSITION',
    -- spiritual content is never freely generated by the model
    free_generation_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE(email, routing_id),
    CHECK(free_generation_allowed = FALSE),
    CHECK(content_source IN ('CURATED_THEOLOGICAL_PROPOSITION','USER_OWN_WORDS'))
);

CREATE TABLE IF NOT EXISTS formation_twin_emd_rules_of_life (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    rule_id VARCHAR(80) NOT NULL,
    capacity VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
    habits_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    deferred_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_habits INTEGER NOT NULL DEFAULT 0 CHECK(total_habits >= 0 AND total_habits <= 10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    UNIQUE(email, rule_id),
    CHECK(capacity IN ('LOW','NORMAL','HIGH'))
);

CREATE TABLE IF NOT EXISTS formation_twin_emd_formation_plans (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    plan_id VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    active_tracks_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    queued_tracks_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    dropped_tracks_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    priority_dimensions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    max_active_tracks INTEGER NOT NULL DEFAULT 3 CHECK(max_active_tracks BETWEEN 1 AND 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE(email, plan_id),
    CHECK(status IN ('READY','SAFETY_FIRST','RUNNING','COMPLETED','PAUSED'))
);

CREATE TABLE IF NOT EXISTS formation_twin_emd_pastoral_summaries (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    summary_id VARCHAR(80) NOT NULL,
    recipient_label VARCHAR(80) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT_AWAITING_USER_PREVIEW',
    content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    excluded_fields_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    user_approved BOOLEAN NOT NULL DEFAULT FALSE,
    -- the system never sends a summary on its own
    auto_sent BOOLEAN NOT NULL DEFAULT FALSE,
    shared_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE(email, summary_id),
    CHECK(status IN ('DRAFT_AWAITING_USER_PREVIEW','APPROVED','SHARED','EXPIRED','REVOKED','DISCARDED','BLOCKED_NO_CONSENT')),
    CHECK(auto_sent = FALSE),
    -- a shared summary always carries an expiry and an explicit user approval
    CHECK(status <> 'SHARED' OR (expires_at IS NOT NULL AND user_approved = TRUE))
);
CREATE INDEX IF NOT EXISTS idx_ft_emd_summary_owner ON formation_twin_emd_pastoral_summaries(email,status,created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS formation_twin_emd_handoffs (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    handoff_id VARCHAR(80) NOT NULL,
    targets_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    signals_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    church_involved_in_harm BOOLEAN NOT NULL DEFAULT FALSE,
    user_consented BOOLEAN NOT NULL DEFAULT FALSE,
    -- the system never initiates contact
    auto_contact BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE(email, handoff_id),
    CHECK(auto_contact = FALSE)
);

CREATE TABLE IF NOT EXISTS formation_twin_emd_group_practices (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    practice_id VARCHAR(80) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    group_size INTEGER NOT NULL DEFAULT 0 CHECK(group_size >= 0),
    status VARCHAR(12) NOT NULL DEFAULT 'READY',
    opt_in BOOLEAN NOT NULL DEFAULT TRUE,
    -- disclosure is never required and leaders never see private records
    disclosure_required BOOLEAN NOT NULL DEFAULT FALSE,
    leader_record_access BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    UNIQUE(email, practice_id),
    CHECK(status IN ('READY','REJECTED','ACTIVE','ENDED')),
    CHECK(disclosure_required = FALSE),
    CHECK(leader_record_access = FALSE)
);

CREATE TABLE IF NOT EXISTS formation_twin_emd_community_feedback (
    id UUID PRIMARY KEY, tenant_id TEXT NOT NULL, profile_id TEXT NOT NULL, email TEXT NOT NULL,
    reconciliation_id VARCHAR(80) NOT NULL,
    feedback_id VARCHAR(80) NOT NULL,
    power_level VARCHAR(20) NOT NULL DEFAULT 'PEER',
    observation VARCHAR(240) NOT NULL,
    weight NUMERIC NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'OBSERVATION_ONLY',
    exclusion_reason VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), deleted_at TIMESTAMPTZ,
    CHECK(power_level IN ('PEER','MODERATE_AUTHORITY','HIGH_AUTHORITY')),
    CHECK(status IN ('OBSERVATION_ONLY','EXCLUDED')),
    -- community feedback can never outweigh the user's own evidence
    CHECK(weight >= 0 AND weight <= 0.3)
);
CREATE INDEX IF NOT EXISTS idx_ft_emd_feedback_owner ON formation_twin_emd_community_feedback(email,created_at DESC) WHERE deleted_at IS NULL;

-- Owner RLS is defense in depth; application queries also retain email predicates.
DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'formation_twin_emd_twin_bridges','formation_twin_emd_identity_alignments',
    'formation_twin_emd_prayer_routings','formation_twin_emd_rules_of_life',
    'formation_twin_emd_formation_plans','formation_twin_emd_pastoral_summaries',
    'formation_twin_emd_handoffs','formation_twin_emd_group_practices',
    'formation_twin_emd_community_feedback'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('DROP POLICY IF EXISTS ft_owner_policy ON %I', table_name);
    EXECUTE format(
      'CREATE POLICY ft_owner_policy ON %I USING (email=current_setting(''app.current_user_email'',true)) '
      'WITH CHECK (email=current_setting(''app.current_user_email'',true))', table_name
    );
  END LOOP;
END $$;
