"""SFDS v3 — Pattern Library Part 1: Categories A (Fear) + B (Pride) + C (Shame)"""

_LOOPS_A_B_C = [

    # ══════════════════════════════════════════════════════════
    # CATEGORY A — FEAR-BASED LOOPS (1–10)
    # ══════════════════════════════════════════════════════════
    {   # A01
        "id": "A01_fear_control_burnout", "label": "Fear → Control → Burnout Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Surrender control illusion; rest before decisions",
        "description": "Fear drives control → overwork → burnout → fear.",
        "chain": ["fear", "control_drive", "overwork", "burnout"],
        "edges": [
            ("fear", "CAUSES", "control_drive"), ("control_drive", "LEADS_TO", "overwork"),
            ("overwork", "LEADS_TO", "burnout"),  ("burnout", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_trust_rest", "BREAKS", "control_drive"),
                        ("principle_uncertainty_accept", "BREAKS", "overwork")],
        "formation_dims": {"fear_tendency": "+", "emotional_stability": "-", "resilience": "-"},
    },
    {   # A02
        "id": "A02_fear_avoidance_anxiety", "label": "Fear → Avoidance → Anxiety Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Take one small truthful action",
        "description": "Fear → avoidance → delay → pressure → anxiety → fear.",
        "chain": ["fear", "avoidance", "delay", "pressure", "anxiety"],
        "edges": [
            ("fear", "CAUSES", "avoidance"), ("avoidance", "LEADS_TO", "delay"),
            ("delay", "LEADS_TO", "pressure"), ("pressure", "LEADS_TO", "anxiety"),
            ("anxiety", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_small_action", "BREAKS", "avoidance")],
        "formation_dims": {"fear_tendency": "+", "truth_alignment": "-", "resilience": "-"},
    },
    {   # A03
        "id": "A03_fear_overplanning_paralysis", "label": "Fear → Overplanning → Paralysis Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Act before certainty is guaranteed",
        "description": "Fear drives endless analysis as a substitute for action. Paralysis → regret → fear.",
        "chain": ["fear", "overthinking", "no_action", "regret"],
        "edges": [
            ("fear", "CAUSES", "overthinking"), ("overthinking", "LEADS_TO", "no_action"),
            ("no_action", "LEADS_TO", "regret"), ("regret", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_action_before_certainty", "BREAKS", "overthinking")],
        "formation_dims": {"fear_tendency": "+", "emotional_stability": "-", "truth_alignment": "-"},
    },
    {   # A04
        "id": "A04_fear_people_pleasing_resentment", "label": "Fear → People-Pleasing → Resentment Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Boundary setting grounded in identity, not approval",
        "description": "Fear of disapproval → approval-seeking → self-neglect → resentment → fear.",
        "chain": ["fear", "approval_seeking", "self_neglect", "resentment"],
        "edges": [
            ("fear", "CAUSES", "approval_seeking"), ("approval_seeking", "LEADS_TO", "self_neglect"),
            ("self_neglect", "LEADS_TO", "resentment"), ("resentment", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_boundary_setting", "BREAKS", "approval_seeking"),
                        ("principle_identity_groundedness", "BREAKS", "approval_seeking")],
        "formation_dims": {"fear_tendency": "+", "relational_health": "-", "humility": "-"},
    },
    {   # A05
        "id": "A05_fear_information_addiction_confusion", "label": "Fear → Information Addiction → Confusion Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Stop input, start one concrete action",
        "description": "Fear drives excessive info consumption seeking certainty → overload → confusion → fear.",
        "chain": ["fear", "excessive_research", "information_overload", "confusion"],
        "edges": [
            ("fear", "CAUSES", "excessive_research"),
            ("excessive_research", "LEADS_TO", "information_overload"),
            ("information_overload", "LEADS_TO", "confusion"), ("confusion", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_action_before_certainty", "BREAKS", "excessive_research")],
        "formation_dims": {"fear_tendency": "+", "truth_alignment": "-", "spiritual_clarity": "-"},
    },
    {   # A06
        "id": "A06_fear_financial_hoarding_insecurity", "label": "Fear → Financial Hoarding → Insecurity Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Generosity interrupts scarcity mindset",
        "description": "Fear of scarcity → hoarding → missed opportunities → insecurity → fear.",
        "chain": ["fear", "hoarding_behavior", "missed_opportunities", "insecurity"],
        "edges": [
            ("fear", "CAUSES", "hoarding_behavior"),
            ("hoarding_behavior", "LEADS_TO", "missed_opportunities"),
            ("missed_opportunities", "LEADS_TO", "insecurity"), ("insecurity", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_generosity", "BREAKS", "hoarding_behavior")],
        "formation_dims": {"fear_tendency": "+", "truth_alignment": "-"},
    },
    {   # A07
        "id": "A07_fear_social_withdrawal_isolation", "label": "Fear → Social Withdrawal → Isolation Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "One small relational act of presence",
        "description": "Fear of rejection → withdrawal → loneliness → amplified fear.",
        "chain": ["fear", "social_withdrawal", "loneliness", "fear_increase"],
        "edges": [
            ("fear", "CAUSES", "social_withdrawal"), ("social_withdrawal", "LEADS_TO", "loneliness"),
            ("loneliness", "LEADS_TO", "fear_increase"), ("fear_increase", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_relational_presence", "BREAKS", "social_withdrawal")],
        "formation_dims": {"fear_tendency": "+", "relational_health": "-"},
    },
    {   # A08
        "id": "A08_fear_defensive_aggression_conflict", "label": "Fear → Defensive Aggression → Conflict Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Pause before defense; name the fear beneath",
        "description": "Fear → defensiveness → conflict → guilt → fear.",
        "chain": ["fear", "defensiveness", "conflict", "guilt"],
        "edges": [
            ("fear", "CAUSES", "defensiveness"), ("defensiveness", "LEADS_TO", "conflict"),
            ("conflict", "LEADS_TO", "guilt"), ("guilt", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_vulnerability_naming", "BREAKS", "defensiveness")],
        "formation_dims": {"fear_tendency": "+", "relational_health": "-", "emotional_stability": "-"},
    },
    {   # A09
        "id": "A09_fear_perfectionism_inaction", "label": "Fear → Perfectionism → Inaction Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Done is better than perfect; progress over protection",
        "description": "Fear of failure → perfectionism → delay → shame → fear.",
        "chain": ["fear", "perfectionism", "delay", "shame"],
        "edges": [
            ("fear", "CAUSES", "perfectionism"), ("perfectionism", "LEADS_TO", "delay"),
            ("delay", "LEADS_TO", "shame"), ("shame", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_progress_over_protection", "BREAKS", "perfectionism")],
        "formation_dims": {"fear_tendency": "+", "truth_alignment": "-", "resilience": "-"},
    },
    {   # A10
        "id": "A10_fear_control_others_relational_breakdown", "label": "Fear → Controlling Others → Relationship Breakdown Loop",
        "category": "fear", "loop_type": "fear_control_loop", "trigger_emotion": "fear",
        "break_principle": "Release control of others; trust their agency",
        "description": "Fear → controlling behavior → resistance → relational damage → fear.",
        "chain": ["fear", "controlling_behavior", "resistance", "relational_damage"],
        "edges": [
            ("fear", "CAUSES", "controlling_behavior"),
            ("controlling_behavior", "LEADS_TO", "resistance"),
            ("resistance", "LEADS_TO", "relational_damage"),
            ("relational_damage", "REINFORCES", "fear"),
        ],
        "break_edges": [("principle_release_control", "BREAKS", "controlling_behavior")],
        "formation_dims": {"fear_tendency": "+", "relational_health": "-", "humility": "-"},
    },

    # ══════════════════════════════════════════════════════════
    # CATEGORY B — PRIDE-BASED LOOPS (11–20)
    # ══════════════════════════════════════════════════════════
    {   # B11
        "id": "B11_pride_comparison_anxiety", "label": "Pride → Comparison → Anxiety Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Gratitude interrupts the comparison mechanism",
        "description": "Pride → comparison → inadequacy → anxiety → pride repair attempt.",
        "chain": ["pride", "comparison", "inadequacy", "anxiety", "pride_repair"],
        "edges": [
            ("pride", "CAUSES", "comparison"), ("comparison", "LEADS_TO", "inadequacy"),
            ("inadequacy", "LEADS_TO", "anxiety"), ("anxiety", "LEADS_TO", "pride_repair"),
            ("pride_repair", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_gratitude", "BREAKS", "comparison")],
        "formation_dims": {"pride_tendency": "+", "emotional_stability": "-", "humility": "-"},
    },
    {   # B12
        "id": "B12_pride_overconfidence_failure", "label": "Pride → Overconfidence → Failure → Shame Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Honest self-assessment before commitment",
        "description": "Pride distorts risk perception → overconfidence → failure → shame → pride defense.",
        "chain": ["pride", "overconfidence", "failure", "shame", "pride_defense"],
        "edges": [
            ("pride", "CAUSES", "overconfidence"), ("overconfidence", "LEADS_TO", "failure"),
            ("failure", "LEADS_TO", "shame"), ("shame", "LEADS_TO", "pride_defense"),
            ("pride_defense", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_honest_self_assessment", "BREAKS", "overconfidence")],
        "formation_dims": {"pride_tendency": "+", "humility": "-", "truth_alignment": "-"},
    },
    {   # B13
        "id": "B13_pride_invalidation_isolation", "label": "Pride → Invalidation of Others → Isolation Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Genuine curiosity about others' perspective",
        "description": "Pride dismisses others → relational loss → loneliness → pride.",
        "chain": ["pride", "dismissing_others", "relational_loss", "loneliness"],
        "edges": [
            ("pride", "CAUSES", "dismissing_others"), ("dismissing_others", "LEADS_TO", "relational_loss"),
            ("relational_loss", "LEADS_TO", "loneliness"), ("loneliness", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_genuine_curiosity", "BREAKS", "dismissing_others")],
        "formation_dims": {"pride_tendency": "+", "relational_health": "-", "humility": "-"},
    },
    {   # B14
        "id": "B14_pride_image_management_exhaustion", "label": "Pride → Image Management → Exhaustion Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Vulnerability reduces the cost of the false self",
        "description": "Pride demands persona maintenance → performance anxiety → exhaustion → emptiness.",
        "chain": ["pride", "image_management", "performance_anxiety", "exhaustion", "emptiness"],
        "edges": [
            ("pride", "CAUSES", "image_management"),
            ("image_management", "LEADS_TO", "performance_anxiety"),
            ("performance_anxiety", "LEADS_TO", "exhaustion"),
            ("exhaustion", "LEADS_TO", "emptiness"), ("emptiness", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_vulnerability", "BREAKS", "image_management")],
        "formation_dims": {"pride_tendency": "+", "emotional_stability": "-", "spiritual_clarity": "-"},
    },
    {   # B15
        "id": "B15_pride_argument_addiction_conflict", "label": "Pride → Argument Addiction → Conflict Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Choose connection over being right",
        "description": "Pride → need to win → conflict → broken trust → pride.",
        "chain": ["pride", "need_to_win", "conflict", "broken_trust"],
        "edges": [
            ("pride", "CAUSES", "need_to_win"), ("need_to_win", "LEADS_TO", "conflict"),
            ("conflict", "LEADS_TO", "broken_trust"), ("broken_trust", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_connection_over_winning", "BREAKS", "need_to_win")],
        "formation_dims": {"pride_tendency": "+", "relational_health": "-", "humility": "-"},
    },
    {   # B16
        "id": "B16_pride_overcommitment_burnout", "label": "Pride → Overcommitment → Burnout Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Rest is not failure — it restores sustainable capacity",
        "description": "Pride prevents saying no → overload → burnout → pride-driven recovery.",
        "chain": ["pride", "inability_to_say_no", "overload", "burnout", "pride_recovery"],
        "edges": [
            ("pride", "CAUSES", "inability_to_say_no"),
            ("inability_to_say_no", "LEADS_TO", "overload"),
            ("overload", "LEADS_TO", "burnout"),
            ("burnout", "LEADS_TO", "pride_recovery"), ("pride_recovery", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_rest_resilience", "BREAKS", "inability_to_say_no")],
        "formation_dims": {"pride_tendency": "+", "resilience": "-", "emotional_stability": "-"},
    },
    {   # B17
        "id": "B17_pride_spiritual_performance_emptiness", "label": "Pride → Spiritual Performance → Emptiness Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Inward orientation over outward performance",
        "description": "Pride → outward spirituality → internal dryness → collapse.",
        "chain": ["pride", "outward_spirituality", "internal_dryness", "collapse"],
        "edges": [
            ("pride", "CAUSES", "outward_spirituality"),
            ("outward_spirituality", "LEADS_TO", "internal_dryness"),
            ("internal_dryness", "LEADS_TO", "collapse"), ("collapse", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_inner_orientation", "BREAKS", "outward_spirituality")],
        "formation_dims": {"pride_tendency": "+", "spiritual_clarity": "-", "truth_alignment": "-"},
    },
    {   # B18
        "id": "B18_pride_self_sufficiency_isolation", "label": "Pride → Self-Sufficiency Illusion → Isolation Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Receiving help is strength, not weakness",
        "description": "Pride rejects dependence → rejection of help → isolation → vulnerability → pride.",
        "chain": ["pride", "self_sufficiency", "rejection_of_help", "isolation", "vulnerability"],
        "edges": [
            ("pride", "CAUSES", "self_sufficiency"),
            ("self_sufficiency", "LEADS_TO", "rejection_of_help"),
            ("rejection_of_help", "LEADS_TO", "isolation"),
            ("isolation", "LEADS_TO", "vulnerability"), ("vulnerability", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_receiving_help", "BREAKS", "self_sufficiency")],
        "formation_dims": {"pride_tendency": "+", "relational_health": "-", "humility": "-"},
    },
    {   # B19
        "id": "B19_pride_self_criticism_shame_cycle", "label": "Pride → Self-Criticism → Shame Cycle",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Self-compassion disrupts the harsh inner standard",
        "description": "Pride → impossible standards → self-criticism → shame → pride defense.",
        "chain": ["pride", "impossible_standards", "self_criticism", "shame"],
        "edges": [
            ("pride", "CAUSES", "impossible_standards"),
            ("impossible_standards", "LEADS_TO", "self_criticism"),
            ("self_criticism", "LEADS_TO", "shame"), ("shame", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_self_compassion", "BREAKS", "impossible_standards")],
        "formation_dims": {"pride_tendency": "+", "humility": "-", "truth_alignment": "-"},
    },
    {   # B20
        "id": "B20_pride_identity_inflation_collapse", "label": "Pride → Identity Inflation → Collapse Loop",
        "category": "pride", "loop_type": "pride_comparison_loop", "trigger_emotion": "pride",
        "break_principle": "Identity grounded in being, not achieving",
        "description": "Pride inflates identity through achievement. Puncture → collapse → reconstruction.",
        "chain": ["pride", "identity_inflation", "identity_puncture", "collapse", "reconstruction"],
        "edges": [
            ("pride", "CAUSES", "identity_inflation"),
            ("identity_inflation", "LEADS_TO", "identity_puncture"),
            ("identity_puncture", "LEADS_TO", "collapse"),
            ("collapse", "LEADS_TO", "reconstruction"), ("reconstruction", "REINFORCES", "pride"),
        ],
        "break_edges": [("principle_being_not_achieving", "BREAKS", "identity_inflation")],
        "formation_dims": {"pride_tendency": "+", "spiritual_clarity": "-", "humility": "-"},
    },

    # ══════════════════════════════════════════════════════════
    # CATEGORY C — SHAME / AVOIDANCE LOOPS (21–30)
    # ══════════════════════════════════════════════════════════
    {   # C21
        "id": "C21_shame_avoidance_delay", "label": "Shame → Avoidance → Delay Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "One small honest step reduces shame's structural power",
        "description": "Shame → avoidance → delay → mounting pressure → shame.",
        "chain": ["shame", "avoidance", "delay", "mounting_pressure"],
        "edges": [
            ("shame", "CAUSES", "avoidance"), ("avoidance", "LEADS_TO", "delay"),
            ("delay", "LEADS_TO", "mounting_pressure"), ("mounting_pressure", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_small_honest_step", "BREAKS", "avoidance")],
        "formation_dims": {"truth_alignment": "-", "resilience": "-", "fear_tendency": "+"},
    },
    {   # C22
        "id": "C22_shame_hiding_increased_pressure", "label": "Shame → Hiding → Increased Pressure Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Disclosure to safe person reduces hiding's compressive force",
        "description": "Shame → hiding → concealment pressure → forced exposure → shame.",
        "chain": ["shame", "hiding", "concealment_pressure", "forced_exposure"],
        "edges": [
            ("shame", "CAUSES", "hiding"), ("hiding", "LEADS_TO", "concealment_pressure"),
            ("concealment_pressure", "LEADS_TO", "forced_exposure"),
            ("forced_exposure", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_safe_disclosure", "BREAKS", "hiding")],
        "formation_dims": {"truth_alignment": "-", "relational_health": "-"},
    },
    {   # C23
        "id": "C23_shame_self_isolation_deterioration", "label": "Shame → Self-Isolation → Emotional Deterioration Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Connection is the primary antidote to shame",
        "description": "Shame → self-isolation → emotional deterioration → shame amplification.",
        "chain": ["shame", "self_isolation", "emotional_deterioration", "shame_amplification"],
        "edges": [
            ("shame", "CAUSES", "self_isolation"),
            ("self_isolation", "LEADS_TO", "emotional_deterioration"),
            ("emotional_deterioration", "LEADS_TO", "shame_amplification"),
            ("shame_amplification", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_connection_antidote", "BREAKS", "self_isolation")],
        "formation_dims": {"relational_health": "-", "spiritual_clarity": "-", "resilience": "-"},
    },
    {   # C24
        "id": "C24_shame_overcompensation_exhaustion", "label": "Shame → Overcompensation → Exhaustion Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Enough-ness: performance cannot permanently resolve shame",
        "description": "Shame → overperformance → exhaustion → inadequacy return → shame.",
        "chain": ["shame", "overperformance", "exhaustion", "inadequacy_return"],
        "edges": [
            ("shame", "CAUSES", "overperformance"), ("overperformance", "LEADS_TO", "exhaustion"),
            ("exhaustion", "LEADS_TO", "inadequacy_return"),
            ("inadequacy_return", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_enough_ness", "BREAKS", "overperformance")],
        "formation_dims": {"emotional_stability": "-", "resilience": "-", "truth_alignment": "-"},
    },
    {   # C25
        "id": "C25_shame_procrastination_anxiety", "label": "Shame → Procrastination → Anxiety Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Begin before the shame thought completes",
        "description": "Shame → procrastination → undone tasks → anxiety → shame.",
        "chain": ["shame", "procrastination", "undone_tasks", "anxiety"],
        "edges": [
            ("shame", "CAUSES", "procrastination"), ("procrastination", "LEADS_TO", "undone_tasks"),
            ("undone_tasks", "LEADS_TO", "anxiety"), ("anxiety", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_start_before_ready", "BREAKS", "procrastination")],
        "formation_dims": {"fear_tendency": "+", "resilience": "-", "truth_alignment": "-"},
    },
    {   # C26
        "id": "C26_shame_perfectionism_paralysis", "label": "Shame → Perfectionism → Paralysis Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Imperfect action is better than perfect silence",
        "description": "Shame → perfectionism → paralysis → inaction shame → shame.",
        "chain": ["shame", "perfectionism", "paralysis", "inaction_shame"],
        "edges": [
            ("shame", "CAUSES", "perfectionism"), ("perfectionism", "LEADS_TO", "paralysis"),
            ("paralysis", "LEADS_TO", "inaction_shame"), ("inaction_shame", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_imperfect_action", "BREAKS", "perfectionism")],
        "formation_dims": {"truth_alignment": "-", "resilience": "-"},
    },
    {   # C27
        "id": "C27_shame_self_criticism_inaction", "label": "Shame → Self-Criticism → Inaction Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Self-compassion is the entry point, not self-justification",
        "description": "Shame → self-criticism → energy depletion → inaction → shame.",
        "chain": ["shame", "self_criticism", "energy_depletion", "inaction"],
        "edges": [
            ("shame", "CAUSES", "self_criticism"), ("self_criticism", "LEADS_TO", "energy_depletion"),
            ("energy_depletion", "LEADS_TO", "inaction"), ("inaction", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_self_compassion", "BREAKS", "self_criticism")],
        "formation_dims": {"resilience": "-", "truth_alignment": "-", "humility": "-"},
    },
    {   # C28
        "id": "C28_shame_escapism_dopamine", "label": "Shame → Escapism → Dopamine Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Name the escape: awareness breaks the automatic trigger",
        "description": "Shame → escapism → dopamine relief → shame return.",
        "chain": ["shame", "escapism", "dopamine_relief", "shame_return"],
        "edges": [
            ("shame", "CAUSES", "escapism"), ("escapism", "LEADS_TO", "dopamine_relief"),
            ("dopamine_relief", "LEADS_TO", "shame_return"), ("shame_return", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_name_the_escape", "BREAKS", "escapism")],
        "formation_dims": {"emotional_stability": "-", "spiritual_clarity": "-", "truth_alignment": "-"},
    },
    {   # C29
        "id": "C29_shame_relationship_withdrawal", "label": "Shame → Relationship Withdrawal Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "One act of repair is more powerful than avoidance",
        "description": "Shame after conflict → withdrawal → relationship damage → shame amplification.",
        "chain": ["shame", "relational_withdrawal", "relationship_damage", "shame_amplification"],
        "edges": [
            ("shame", "CAUSES", "relational_withdrawal"),
            ("relational_withdrawal", "LEADS_TO", "relationship_damage"),
            ("relationship_damage", "LEADS_TO", "shame_amplification"),
            ("shame_amplification", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_repair_act", "BREAKS", "relational_withdrawal")],
        "formation_dims": {"relational_health": "-", "truth_alignment": "-"},
    },
    {   # C30
        "id": "C30_shame_identity_fragmentation", "label": "Shame → Identity Fragmentation Loop",
        "category": "shame", "loop_type": "shame_avoidance_loop", "trigger_emotion": "shame",
        "break_principle": "Identity is not earned; shame cannot cancel it",
        "description": "Shame attacks the sense of self → fragmentation → increased vulnerability → shame.",
        "chain": ["shame", "identity_attack", "fragmentation", "increased_vulnerability"],
        "edges": [
            ("shame", "CAUSES", "identity_attack"), ("identity_attack", "LEADS_TO", "fragmentation"),
            ("fragmentation", "LEADS_TO", "increased_vulnerability"),
            ("increased_vulnerability", "REINFORCES", "shame"),
        ],
        "break_edges": [("principle_identity_groundedness", "BREAKS", "identity_attack")],
        "formation_dims": {"spiritual_clarity": "-", "emotional_stability": "-", "resilience": "-"},
    },
]
