# -*- coding: utf-8 -*-
"""English translations, batch 1 (12 marquee cards). name -> {field: english}.
Applied as lesson_en / summary_en / witness_en / prayer_en / follow_en[] / caution_en[] / applications_en[]."""
EN = {
"亚当": dict(
 lesson="The importance of obedience",
 summary="The first human; through his disobedience he fell and brought sin into the world.",
 witness="Adam is a mirror for all humanity: one choice changed all of history. God gave him a perfect environment and a clear command, yet he still chose his own will over God's. His tragedy was not some great crime, but staying silent before a small temptation—watching, then following.",
 follow=["Entrusted with caring for creation, with real responsibility","Able to give a truthful account when asked"],
 caution=["Staying silent in the face of temptation","Shifting the blame to others (to Eve, and to God)","Refusing to face his own sin"],
 applications=["When facing temptation, first pause and ask: does this align with God's will?","In relationships, don't shirk responsibility—own your mistakes","Read a portion of God's word daily so His commands stay clear in your heart","Under pressure, don't stay silent—speak out the right stand","After sinning, confess directly to God instead of hiding"],
 prayer="Lord Jesus, You are the second Adam who mended Adam's rebellion through obedience. Help me in every choice I face today to choose Your will over my own desires. When I want to shift the blame, remind me of Your cross. Amen."),
"挪亚": dict(
 lesson="Obedience in adversity",
 summary="In an age when the whole earth was corrupt, by faith he obeyed God and built the ark; his whole family was saved, and he became the starting point of a new humanity.",
 witness="Noah's obedience looked absurd at the time—no sign of a flood, no one's support, likely decades of ridicule. Yet he did every step exactly as God said, without discount or revision. That is faith: acting while still unable to see, needing no one else's understanding.",
 follow=["Obeying God with no social support whatsoever","Completing God's instructions step by step, without cutting corners or altering the plan","Being the spiritual leader of his family, leading them all to safety"],
 caution=["Got drunk and was shamed after the flood—weakness in his later years"],
 applications=["When God gives clear guidance, act without waiting to 'feel ready'","Keep doing what God told you even when others mock and misunderstand","Take up the responsibility of spiritual leadership in your home, daily","After a great success, stay watchful against the weakness that comes with letting your guard down","Is there something God has already told you to do, but you haven't begun?"],
 prayer="Lord, Noah's faith was a faith that acted. Let me stop waiting when You give me clear guidance, and obey at once. Give me Noah's perseverance when others don't understand, and watchfulness after success. Amen."),
"亚伯拉罕": dict(
 lesson="Faith that responds to God's call",
 summary="The father of faith; called by God to leave his homeland, he believed an impossible promise, was counted righteous, and became the father of many nations.",
 witness="Abraham is the ultimate example of faith. God said go, and he set out not knowing where. God promised him a son, and at a hundred years old he still believed. God told him to offer Isaac, and the hand that raised the knife shows he truly believed God could raise the dead. Faith is not a feeling; it is action.",
 follow=["Responding immediately to God's call, not waiting for perfect conditions","Still believing God's promise in old age and barrenness","Trusting God fully on Mount Moriah, willing to offer even Isaac"],
 caution=["Out of fear, lying that his wife was his sister (twice)","Fathering Ishmael through Hagar—trying to fulfill God's promise by human means"],
 applications=["When God calls, don't wait for perfect conditions—take the first step","While waiting for the promise, don't try to help God by human schemes","In the hardest demands, choose to trust God's character and faithfulness","When afraid, be honest with God rather than protecting yourself with lies","Tell yourself: God's promise is more real than my circumstances"],
 prayer="Lord, Abraham's faith is my goal. When You call me out, help me set out without waiting for a map. When I face my 'Isaac,' let my trust run deeper than my love. When I am afraid, let me be honest with You instead of turning to lies. Amen."),
"摩西": dict(
 lesson="Humble leadership",
 summary="The great prophet who led Israel out of Egypt; called the most humble man on earth, the supreme model of humble leadership.",
 witness="Moses' life had three parts: in the first forty years he thought he was somebody; in the middle forty God showed him he was nobody; in the last forty God accomplished through him one of humanity's greatest stories of redemption. A true leader rests not on ability, but on the humility of God's presence.",
 follow=["Called the most humble man on all the earth","Faithfully interceding for the people even under enormous pressure","Speaking with God face to face—the most intimate relationship"],
 caution=["Striking the rock in the wilderness, disobeying God's command, and so not entering the promised land","Impulsively killing an Egyptian in his early years"],
 applications=["A leader's authority comes from relationship with God, not personal charisma","When representing others, be willing to speak and intercede for them","Under pressure, don't act on emotion—seek God first","Humility is not lack of ability, but knowing the source of ability","Is there something today you want to solve in your own strength? Pray first"],
 prayer="Lord, Moses was the humble vessel You used to lead. Let me understand that true leadership comes from drawing near to You, not from my ability or position. When I want to fix things on my own, remind me to seek You first. Amen."),
"大卫": dict(
 lesson="Repentance and worship after God's heart",
 summary="A king after God's own heart who committed grave sins of adultery and murder, yet repented genuinely and became the greatest worshipper of the Old Testament.",
 witness="David's sins were not light—adultery, lies, murder. Yet God called him a man after His own heart, not because he was perfect, but because his heart toward God was real. Psalm 51 is humanity's most profound prayer of repentance. What God values is not the absence of failure, but a genuine turning back after failure.",
 follow=["A real, deep, song-like love for God","Habitually turning to God in prayer in both victory and suffering","Repenting genuinely after falling, without self-justification"],
 caution=["Committing adultery with Bathsheba and killing Uriah","Favoritism toward his sons, failing in family discipline","Failing to deal with his son Absalom's sin in his later years"],
 applications=["Express your love for God continually through song, prayer, and thanksgiving","After sinning, don't justify yourself—confess directly to God","Build a daily habit before God, making repentance a way of life","True repentance brings concrete change, not just a feeling of shame","God looks at the heart—where is your heart today?"],
 prayer="Lord, David's psalms are my truest dictionary of prayer. Create in me a clean heart, O God, and renew a right spirit within me. After I fall, help me return to You genuinely like David—without covering up, without self-defense. Amen."),
"以斯帖": dict(
 lesson="Risking yourself for your people",
 summary="A Jewish orphan in the Persian court; when Haman plotted to annihilate the Jews, she risked death to enter the king's presence and plead for them, saving her whole people. Her position was God's preparation.",
 witness="Mordecai said: who knows whether you have come to the kingdom for such a time as this? Esther's reply: if I perish, I perish. Her position was no coincidence but God's arrangement; her action was no impulse but obedience after three days of fasting and prayer.",
 follow=["Recognizing that her position was for God's purpose","Preparing to face the greatest danger with three days of fasting and prayer","Stepping forward and risking her life for others"],
 caution=[],
 applications=["Who knows—might your present position also be God's arrangement for some purpose?","Staying silent at the decisive moment may not keep you safe after all","In your position today, is there something or someone you could speak up for?","Fast and pray, then act—neither acting instead of praying, nor praying instead of acting"],
 prayer="Lord, at the most dangerous moment Esther said: if I perish, I perish. Help me not to be silent out of fear at the decisive moment, trusting that You have placed me here for a purpose. Amen."),
"但以理": dict(
 lesson="Holding fast without compromise in the workplace",
 summary="A Hebrew youth exiled to Babylon who kept his faith across two dynasties; thrown into the lions' den for praying yet unharmed, he left a double witness of prophetic visions and blameless character.",
 witness="Three times a day he opened his window toward Jerusalem and prayed—he knew the decree, and still did as he always had. This was not defiance, but simply his way of life; a decree could not change his habit. Faith is not practiced only when permitted; it is the normal state of life.",
 follow=["Keeping blameless character even at the height of his career","Praying three times a day as a way of life, unchanged by circumstances","Refusing to trade truth for political safety through compromise"],
 caution=[],
 applications=["Is your spiritual discipline a way of life, or conditional?","Under pressure and prohibition, which spiritual habit do you give up first?","Integrity at work: what do you choose when no one is watching?","Set a fixed time to pray today, and don't cancel it for busyness"],
 prayer="Lord, Daniel prayed three times a day even facing the lions' den. Help me build prayer into a way of life, not crying out to You only in crisis. Amen."),
"马利亚": dict(
 lesson="Full surrender to God's will",
 summary="The mother of Jesus. When the angel announced she would conceive by the Holy Spirit, she said: I am the Lord's servant; may it be to me according to your word. Surrender amid total uncertainty is the ultimate act of faith.",
 witness="The angel's announcement carried every risk. Yet she said: I am the Lord's servant; may it be to me according to your word. She treasured the words of Jesus and pondered them in her heart. Surrender is not passive; it is a wholehearted yes to a wonder she could not fully understand.",
 follow=["Saying 'may it be to me according to your word' amid total uncertainty","Treasuring God's words in her heart and pondering them, not seeking display","Staying by Jesus' side throughout His public ministry"],
 caution=[],
 applications=["Mary's surrender held both the unknown and a cost—what unknown are you facing now?","Treasure God's word in your heart; you need not understand at once—first ponder and keep it","In costly obedience, what is your greatest obstacle?","Say it once today, in a small way: Lord, may it be to me according to Your word."],
 prayer="Lord, Mary said yes without knowing the outcome. Help me not to wait until I understand before I obey Your call—let me first say: may it be to me according to Your word. Amen."),
"彼得": dict(
 lesson="From denial to restoration",
 summary="From fisherman to rock; he denied the Lord, but after being restored became a pillar of the early church.",
 witness="Peter's life holds both an example to follow and a warning to heed. God's restoration can surpass our greatest failures.",
 follow=["Hearing Jesus' call, immediately leaving his nets to follow—decisive, without hesitation","The first to openly confess, 'You are the Christ, the Son of the living God' (Matt 16:16)","After falling, not despairing like Judas, but receiving the Lord's threefold 'do you love me?' restoration and being rebuilt","After being filled with the Spirit at Pentecost, standing firm—one sermon, three thousand saved"],
 caution=["Overconfident, boasting 'though all fall away, I never will,' yet denying the Lord three times that very night","Acting in the flesh, cutting off Malchus' ear","Out of fear of the Jews, playing the hypocrite and withdrawing before Gentiles, opposed by Paul to his face (Gal 2:11-14)"],
 applications=["Have you denied what you believe under pressure? Peter's restoration tells you: the Lord's forgiveness is still open to you","Stand not by self-confident resolve but by the Spirit's power—human strength cannot be relied on","After falling, don't stay in self-blame; hear the Lord ask 'do you love me?' and return to His service"],
 prayer="Lord, after I denied You, You still asked me, 'do you love me?' Thank You for Your restoration. Amen."),
"保罗": dict(
 lesson="Grace that radically transforms a life",
 summary="From the most violent persecutor of the church to the greatest apostle; struck down by the light of Jesus on the Damascus road, he entered decades of vast, bold mission, writing, and church-planting—a life themed on grace.",
 witness="Paul said: I am the foremost of sinners. God's grace did not erase his past, but turned his past into the greatest witness of God's grace. 'I can do all things through Him who strengthens me.'",
 follow=["After his radical transformation at Damascus, beginning to preach at once","Writing Philippians with joy even under chains, imprisonment, and deadly threats","Equipping the church with deep theology, and leading by the example of a lived life"],
 caution=[],
 applications=["Paul's past became God's greatest witness of grace—yours can too","'I can do all things through Him who strengthens me'—what do you need this strength for today?","Write thanksgiving and joy in your hardest circumstances—that is the birthplace of Philippians","Do you think your past mistakes make you unworthy to serve God? Paul's answer: grace is sufficient"],
 prayer="Lord, Paul said he was the foremost of sinners, yet through him You wrote the New Testament's most profound letters. Help me believe my past does not limit Your plan, and Your grace is made perfect in my weakness. Amen."),
"撒玛利亚妇人": dict(
 lesson="One who meets living water becomes one who witnesses",
 summary="The Samaritan woman who met Jesus while drawing water at the well; from discussing living water to recognizing the Christ, she at once left her water jar, went into town to testify, and brought the whole town to the Lord.",
 witness="The Samaritan woman drawing water alone at noon had a broken past (five husbands) and a marginalized identity. Yet Jesus crossed the barriers of race, gender, and morality, asking her for a drink and giving her 'living water': 'whoever drinks the water I give will never thirst.' From avoidance and argument she was won over as the Lord saw through everything, and recognized Him as the Christ. Then she 'left her water jar' and ran back to town: 'Come and see!' Many Samaritans believed in Jesus because of her word. One whom people despised became the earliest city evangelist.",
 follow=["From meeting the Lord to recognizing Him, facing herself honestly","Immediately witnessing to others, bringing people to Jesus","Not shrinking back because of her past or her identity"],
 caution=[],
 applications=["Before the Lord, honestly face your own past and your thirst","Once you have received the Lord, go at once and share with others","Cross your prejudices to care for and invite people to know the Lord","Let others 'come and see'—bring people to Jesus"],
 prayer="Lord Jesus, at the well You gave living water to a despised woman, and she became a witness who brought her town to You. Fill me with Your living water, so that I too may witness freely and bring people to see You. Amen."),
"押尼珥": dict(
 lesson="Talent without devotion to God comes to nothing",
 summary="Saul's army commander; after Saul's death he made Ish-bosheth king, later turned to David, but was killed at Hebron by Joab in a personal vendetta.",
 witness="Abner was a capable, influential man—almost single-handedly he held Saul's dynasty together, and he had the power to bring all Israel over to David. But his loyalty was always to people and to power, not to God's will; he knew God had chosen David, yet for his own advantage propped up Ish-bosheth for years. When he finally turned to David, he died in an old feud. His life is a warning: gifting and political skill, if not submitted to God's will, buy only a sigh in the end—'should Abner die as a fool dies?'",
 follow=["Capable, with leadership that rallies people","Finally willing to acknowledge and submit to the king God anointed"],
 caution=["Knowing God's will, yet delaying obedience for private gain","Devoted to power and people rather than to God's call"],
 applications=["Give your talent and influence to God, and ask how He wants you to use it","Don't delay when you already know God's will, for the sake of advantage","Turn to the right side early; don't wait until the cost is higher","In conflict, seek reconciliation—but also guard against the backlash of old grudges"],
 prayer="Lord, Abner had talent yet was slow to submit to Your will. Keep me from being loyal to power or people, but loyal to Your call alone; let all my gifts be submitted under Your will. Amen."),
}
