"""
MVFE PIPELINE METRICS
Records per-run statistics to mvfe_pipeline_stats table for longitudinal analysis.
Provides aggregation queries for the /api/mvfe/stats endpoint.
"""
from __future__ import annotations

import logging
from typing import Any, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Write path
# ---------------------------------------------------------------------------

def record_pipeline_run(
    db_pool,
    *,
    user_id: str,
    event_id: str,
    pipeline_latency_ms: float,
    formation: dict,
    critic: dict,
    governance: dict,
    emotion: dict,
) -> None:
    """Persist one MVFE pipeline run to mvfe_pipeline_stats.

    Args:
        db_pool: psycopg2 ThreadedConnectionPool
        user_id: authenticated user identifier
        event_id: UUID generated by orchestrator for this run
        pipeline_latency_ms: wall-clock time for full pipeline
        formation: FormationResult as dict
        critic: CriticReport as dict
        governance: GovernanceReport as dict
        emotion: EmotionState as dict
    """
    conn = None
    try:
        conn = db_pool.getconn()
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO mvfe_pipeline_stats (
                    user_id, event_id, pipeline_latency_ms,
                    formation_score, drift_score, stability_score, formation_score_ema,
                    coherence_score, overfit_risk, confidence_adjustment,
                    governance_passed, governance_violations, governance_risk_level,
                    primary_emotion, emotion_intensity, emotion_uncertainty
                ) VALUES (
                    %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s
                )
                ON CONFLICT (event_id) DO NOTHING
                """,
                (
                    user_id,
                    event_id,
                    round(pipeline_latency_ms, 1),
                    # formation
                    formation.get("formation_score", 0.0),
                    formation.get("drift_score", 0.0),
                    formation.get("stability_score", 0.0),
                    formation.get("formation_score_ema", 0.0),
                    # critic
                    critic.get("coherence_score", 0.0),
                    critic.get("overfit_risk", 0.0),
                    critic.get("confidence_adjustment", 0.0),
                    # governance
                    governance.get("passed", True),
                    len(governance.get("violations", [])),
                    governance.get("risk_level", "low"),
                    # emotion
                    emotion.get("primary_emotion", ""),
                    emotion.get("intensity", 0.0),
                    emotion.get("uncertainty", 0.0),
                ),
            )
            conn.commit()
    except Exception as exc:
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
        logger.warning(f"[mvfe.metrics] record failed: {exc}")
    finally:
        if conn is not None:
            try:
                db_pool.putconn(conn)
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Read path — aggregate queries
# ---------------------------------------------------------------------------

def get_pipeline_stats(
    db_pool,
    *,
    user_id: Optional[str] = None,
    last_n_days: int = 30,
) -> dict[str, Any]:
    """Aggregate MVFE pipeline stats for the /api/mvfe/stats endpoint.

    Returns::

        {
          "period_days": 30,
          "run_count": 847,
          "avg_latency_ms": 312.4,
          "p95_latency_ms": 780.0,
          "governance": {
            "pass_rate": 0.97,
            "violation_count": 26,
            "risk_level_breakdown": {"low": 821, "medium": 21, "high": 5}
          },
          "critic": {
            "avg_coherence": 0.74,
            "avg_overfit_risk": 0.22
          },
          "formation": {
            "avg_score": 0.61,
            "avg_drift": 0.18,
            "avg_stability": 0.82
          },
          "top_emotions": [
            {"emotion": "焦虑", "count": 134},
            ...
          ]
        }
    """
    conn = None
    try:
        conn = db_pool.getconn()
        with conn.cursor() as cur:
            user_filter = "AND user_id = %s" if user_id else ""
            params_base: list = [last_n_days]
            if user_id:
                params_base.append(user_id)

            # Aggregate
            cur.execute(
                f"""
                SELECT
                    COUNT(*)                                    AS run_count,
                    AVG(pipeline_latency_ms)                   AS avg_latency_ms,
                    PERCENTILE_CONT(0.95) WITHIN GROUP
                        (ORDER BY pipeline_latency_ms)         AS p95_latency_ms,
                    AVG(coherence_score)                       AS avg_coherence,
                    AVG(overfit_risk)                          AS avg_overfit_risk,
                    AVG(confidence_adjustment)                 AS avg_confidence_adj,
                    AVG(formation_score)                       AS avg_formation,
                    AVG(drift_score)                           AS avg_drift,
                    AVG(stability_score)                       AS avg_stability,
                    SUM(CASE WHEN governance_passed THEN 1 ELSE 0 END) AS pass_count,
                    SUM(governance_violations)                 AS total_violations
                FROM mvfe_pipeline_stats
                WHERE created_at >= NOW() - INTERVAL '%s days'
                {user_filter}
                """,
                params_base,
            )
            row = cur.fetchone()
            if not row or row[0] == 0:
                return {"period_days": last_n_days, "run_count": 0}

            (
                run_count, avg_latency, p95_latency,
                avg_coherence, avg_overfit, avg_conf_adj,
                avg_formation, avg_drift, avg_stability,
                pass_count, total_violations,
            ) = row

            # Governance risk breakdown
            cur.execute(
                f"""
                SELECT governance_risk_level, COUNT(*) AS cnt
                FROM mvfe_pipeline_stats
                WHERE created_at >= NOW() - INTERVAL '%s days'
                {user_filter}
                GROUP BY governance_risk_level
                """,
                params_base,
            )
            risk_rows = cur.fetchall()
            risk_breakdown = {r[0]: r[1] for r in risk_rows}

            # Top emotions (up to 10)
            cur.execute(
                f"""
                SELECT primary_emotion, COUNT(*) AS cnt
                FROM mvfe_pipeline_stats
                WHERE created_at >= NOW() - INTERVAL '%s days'
                  AND primary_emotion <> ''
                  {user_filter}
                GROUP BY primary_emotion
                ORDER BY cnt DESC
                LIMIT 10
                """,
                params_base,
            )
            emotion_rows = cur.fetchall()

            return {
                "period_days": last_n_days,
                "run_count": int(run_count),
                "avg_latency_ms": round(float(avg_latency or 0), 1),
                "p95_latency_ms": round(float(p95_latency or 0), 1),
                "governance": {
                    "pass_rate": round(float(pass_count) / float(run_count), 4),
                    "violation_count": int(total_violations or 0),
                    "risk_level_breakdown": {k: int(v) for k, v in risk_breakdown.items()},
                },
                "critic": {
                    "avg_coherence": round(float(avg_coherence or 0), 4),
                    "avg_overfit_risk": round(float(avg_overfit or 0), 4),
                    "avg_confidence_adjustment": round(float(avg_conf_adj or 0), 4),
                },
                "formation": {
                    "avg_score": round(float(avg_formation or 0), 4),
                    "avg_drift": round(float(avg_drift or 0), 4),
                    "avg_stability": round(float(avg_stability or 0), 4),
                },
                "top_emotions": [
                    {"emotion": r[0], "count": int(r[1])} for r in emotion_rows
                ],
            }
    except Exception as exc:
        logger.error(f"[mvfe.metrics] get_pipeline_stats failed: {exc}")
        return {"error": str(exc), "period_days": last_n_days, "run_count": 0}
    finally:
        if conn is not None:
            try:
                db_pool.putconn(conn)
            except Exception:
                pass
